#!/usr/bin/env bash
# Configures Nginx with a custom HTTP header X-Served-By
# The value of the header is the hostname of the server

# Install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Configure default server block
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    add_header X-Served-By \$hostname;

    location / {
        return 200 "Hello World!\n";
    }
}
EOF

# Restart nginx
service nginx restart