#!/usr/bin/env bash
# Configures Nginx with a custom HTTP header X-Served-By
# The value of the header is the hostname of the server

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Get the hostname
# shellcheck disable=SC2154
HOSTNAME=$(hostname)

# Add the custom header to the http block in nginx.conf
sudo sed -i "/http {/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo service nginx restart
