#!/usr/bin/env bash
# Installs and configures HAProxy to balance traffic between web-01 and web-02

# Install HAProxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Enable HAProxy init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null << 'EOF'
global
    log /dev/log local0
    maxconn 2048
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend web-frontend
    bind *:80
    default_backend web-servers

backend web-servers
    balance roundrobin
    server web-01 3.82.209.129:80 check
    server web-02 184.72.182.76:80 check
EOF

# Restart HAProxy
sudo service haproxy restart