#!/usr/bin/env bash
# Configures an Ubuntu machine to install and configure Nginx

apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx restart