#!/usr/bin/env bash
# Installs and configures Nginx web server

apt-get -y update
apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
service nginx restart