#!/usr/bin/env bash
# Installs and configures Nginx to serve a custom page
apt-get -y update
apt-get -y install nginx
printf 'Holberton School for the win!\n' > /var/www/html/index.nginx-debian.html
service nginx restart
