#!/usr/bin/env bash
# Update and install nginx

apt-get update -y
apt-get install -y nginx

# Create default index page
echo "Holberton School for the win!" > /var/www/html/index.html

# Configure redirection
sed -i '/server_name _;/a \
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart