#!/usr/bin/env bash
# Update and install nginx

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo sed -i '/server_name _;/a \
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default
sudo service nginx restart