#!/usr/bin/env bash
# Update and install nginx

sudo apt-get update -y
sudo apt-get install -y nginx

# Create default index page
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure nginx
sudo sed -i '/server_name _;/a \
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }\
    error_page 404 /404.html;\
    location = /404.html {\
        internal;\
    }' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart