#!/usr/bin/env bash
# Update and install nginx

apt-get update -y
apt-get install -y nginx

# Create default index page
echo "Holberton School for the win!" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure nginx
sed -i '/server_name _;/a \
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }\
    error_page 404 /404.html;\
    location = /404.html {\
        internal;\
    }' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart